# Generated by Django 4.2.7 on 2024-01-15 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='title',
            new_name='designation_title',
        ),
    ]
