# Generated by Django 4.2.7 on 2023-12-05 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0002_rename_field_education_field_of_study'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='end_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
