# Generated by Django 4.2.7 on 2024-01-16 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0002_rename_title_experience_designation_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='description',
            new_name='note',
        ),
    ]
