# Generated by Django 4.2.7 on 2024-01-27 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitorization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board', to='monitorization.workspace'),
        ),
    ]
