# Generated by Django 4.2.7 on 2024-01-16 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monitorization', '0003_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspace',
            name='vendor',
        ),
        migrations.AddField(
            model_name='workspace',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
