# Generated by Django 4.2.7 on 2024-01-20 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitorization', '0005_invitetoworkspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='short_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
